### ISSUE TITLE
[develop] Birthdays aren't displayed anymore

### ISSUE THREAD

**Issue by auricgoldfinger** [alexstyl/Memento-Namedays#54]
#### Short Description

On develop branch, birthdays aren't displayed anymore

##### Steps to reproduce
Change the launchpoint to launch `com.alexstyl.specialdates.ui.activity.MainActivity` in stead of the Debug activity
 1. Set a breakpoint in `BirthdayDatabaseRefresher.storeContactsToProvider`
 2. Launch the app from the debug branch
 3. See that the `BirthdayMarshaller.marshall` just returns `new ContentValues[0];` (I'm not entirely sure this is the problem)
 4. Continue the application

##### Resulted in
The app opens without any birthday

##### Expected Results
Birthdays are displayed

##### Video/Screenshots
![scaled_image](https://cloud.githubusercontent.com/assets/2921401/19014800/0b252c46-87f7-11e6-8e9b-0adb11d917ba.jpg)

**Comment by auricgoldfinger** [comment]
I think this is some change that isn't finished yet, but which is already pushed to the `develop` branch :-)
The reason why I bumped into this, is because I was planning to integrate other dates as well. Anniversaries for one, but also custom dates. Not to celebrate at all - I'm keeping dates of deceive as well - but I'd like to get reminded about those dates as well to be able to ease the pain on the anniversary date of a lost one.

So what I see is that you especially introduced a birthday class which I'd like to convert to a more general "ContactEvent" ;-) (I know, you came from that one)
But since the birthdays are fetched in BirthdayDatabaseRefresher, in order to require only one iteration over the contacts, I'd like to retrieve other dates there as well - meaning it isn't only a BirthdayDatabaseRefresher...

**Comment by alexstyl** [comment]
How did that one slipped through? 😅

That is indeed be the problem as you mention. I'll work and get it done asap

The `Birthday` class is not new. It is used to represent the date of Birth rather than the celebration (the name is indeed misleading). The is in fact a `ContactEvent` class which represents the actual celebration of an event. For Birthdays you need both the contact's year of birth *and* their upcoming birthday so that you can calculate the age.

As you mentioned the `BirthdayDatabaseRefresher` could be changed so that it fetches and handles all events from the device rather than just contacts.

I really like the feature(s) you mentioned, and once again thank you so much for your contributions to the project :)

**Comment by alexstyl** [comment]
I am working on a PR that reduces all the different variation of date classes down to one, in an attempt to simplify things.

In my PR I have removed `Birthday`, `AnnualDate`, `ParsedDate` and renamed `DayDate` to `Date` which is the single date class to handle dates, even if that has a year or not. No more weird Date interfaces and multiple date classes. Also, since the `Birthday` class is getting ditched, the date of birth will be represented as an `Optional<Date>` field in the Contact class.

I hope this clear out things a lot. I am planning of pushing this branch later in the date

**Comment by auricgoldfinger** [comment]
Great! I guess the `Optional<Date>` will probably have to become a `List<Optional<Date>>` if we want to keep multiple dates for a contact. But I'm going to wait for the update anyway. No rush, I'll be busy on other stuff anyway (daytime job, family, you know ;-) )

**Comment by alexstyl** [comment]
It is probably even simpler than that :)
There is no place of the app that cases the Birthdays of any contact right now. All data are stored in the database and queried from there when needed. The `Birthday` object was not the celebration event itself, but a date of when the contact was born, so that we can get their age for the running year. 

Anyhow, I'm closing this as it was fixed as part of https://github.com/alexstyl/Memento-Namedays/pull/55
